//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eComBid.API.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public byte[] Password { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string AlternateEmail { get; set; }
        public string Phone { get; set; }
        public string SecondaryPhone { get; set; }
        public Nullable<int> UserType { get; set; }
        public Nullable<int> AddressId { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> SocialMediaSourceId { get; set; }
        public string SocialMediaId { get; set; }
        public System.DateTime DateAdded { get; set; }
        public System.DateTime DateModified { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public string AvatarURL { get; set; }
        public Nullable<bool> IsBuyer { get; set; }
    }
}
